### ISSUE TITLE
Drop ******ASIDE Annotation Request*******

### ISSUE THREAD

**Issue by jssmith1** [UNCCharlotteHCILab/aside_main#13]
Prepend other items with "ASIDE:"

**Comment by CaptainEmerson** [comment]
Actually, looks like it does something when selected. Maybe it should be more clear what it does?

**Comment by tthoma81** [comment]
This should take care of it :)

**Comment by CaptainEmerson** [comment]
Nice, @tthoma81! 

One suggestion: you might want to drop the bin folder. #SoftwareEngineringThings

**Comment by tthoma81** [comment]
Sure, which bin folder?

**Comment by CaptainEmerson** [comment]
https://github.com/UNCCharlotteHCILab/aside_main/tree/master/CodeAnnotate/bin

**Comment by tthoma81** [comment]
Thanks. I had to play with the gitigore file a little bit, but it looks like the bin is now out of the iTrust branch and being ignored (but still available for my ide of course).
