### ISSUE TITLE
Do Formative Study

### ISSUE THREAD

**Issue by jssmith1** [UNCCharlotteHCILab/aside_main#16]
* Create video of fake participant going through study @tthoma81 
* Send feedback on study modifications @jssmith1
* File IRB at UNCC
* File IRB at NCSU (#10)
* Recruit participants
* Include access control unit as part of security lecture at NCSU @CaptainEmerson
* Do study

**Comment by CaptainEmerson** [comment]
@tthoma81 has created a video: https://drive.google.com/folderview?id=0B9PkCcRv1BS5elFWeFFVMVUxX00&usp=sharing

Thanks, @tthoma81! Do you think it would be helpful to have a full experimenter's notebook (e.g. http://multiview.cs.pdx.edu/refactoring/experiments/experiment_files/smell_experimenters_notebook.pdf)? To me, I think that this would make sure we don't miss anything. You've got most of the pieces there, but a full end-to-end protocol would be good.

I've added some feedback in the docs:
https://drive.google.com/drive/u/1/#folders/0B3hJnPYMQtFWUm1PWHVCRlRPNVk

@jssmith1 , please try to run through the experiment, then add comments of your own.

Adding @heather-lipford to the convo.

**Comment by tthoma81** [comment]
No problem :). I hope the video helps out. I think the idea of an experimenter's notebook sounds good. It would definitely help make sure that the interviewer is ready to go before beginning the interview, and it would help collect data. However, for this study, in the interest of time, the cost might outweigh the benefit.

**Comment by jssmith1** [comment]
Finished watching the video and reviewing my notes. I think the next step is for @tthoma81 and me to set up a time to video chat. I want to go over some questions I had about the procedure and making sure I can configure the experiment on my machine.

After we chat, finalize the procedure, and configure my machine. I'd like to run through the study remotely as a participant.

**Comment by tthoma81** [comment]
Sounds great. :) For everyone else who is reading, we are currently setting up a time in email and shooting for early next week.
