### ISSUE TITLE
Integrate newest code to this repository

### ISSUE THREAD

**Issue by jssmith1** [UNCCharlotteHCILab/aside_main#2]
Make sure that this is the most up to date version so that I can work on it

**Comment by tthoma81** [comment]
Done, Repository has been completely revamped.

**Comment by CaptainEmerson** [comment]
@tthoma81 Thanks for taking this on. For future requests that necessitate changes to the repo, could you please associate the commit(s) with the issue?
https://help.github.com/articles/closing-issues-via-commit-messages/
or, if you've already made the commit:
http://stackoverflow.com/questions/8910271/how-can-i-reference-a-commit-in-an-issue-comment-on-github

**Comment by tthoma81** [comment]
No problem. That will allow us to link commits to issues.
